version: '3.8'

services:
  logisticahesego:
    build: .
    container_name: logisticahesego
    restart: unless-stopped
    ports:
      - "8085:80"
    networks:
      - web

networks:
  web:
    external: true
